heat_template_version: 2013-05-23

description: NTNU Datasikkerhet - BeeF XSS Framework Lab

parameters:
  key_name:
    type: string
    description: SSH keypair name

resources:
  private_net:
    type: OS::Neutron::Net

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 192.168.111.0/24
      gateway_ip: 192.168.111.1
      dns_nameservers:
        - 129.241.0.200
        - 129.241.0.201
      allocation_pools:
        - start: 192.168.111.101
          end: 192.168.111.200

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: ntnu-internal

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: private_subnet }

  kali_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security group for BeeF lab
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 3000
          port_range_max: 3000
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 3389
          port_range_max: 3389
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 8080
          port_range_max: 8080

  kali:
    type: OS::Nova::Server
    properties:
      name: kali-beef-lab
      image: 'Kali Linux 2025.2 Minimal amd64'
      flavor: gx3.2c8r
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: kali_port }
      user_data_format: RAW
      user_data: |
        #cloud-config
        package_upgrade: true
        timezone: "Europe/Oslo"
        
        users:
          - default
          - name: student
            passwd: $6$LAN6zc6SMkJlUE7.$s8/5KSXDxGpfd088vZk0//mYXXCNgTlwYFQubH75yHlhTa664jJl24pT2hDw1U8OT2Unc8YTkRGeQqhJ4onL0.
            lock_passwd: false
            gecos: NTNU Student
            groups: sudo
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
            ssh_authorized_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDZG7//kJBzyU+cQI1LTIRmP4umzhCRuOlSM9Oi5gH+0 macbook-demo-key
        
        packages:
          - kali-linux-headless
          - kali-desktop-xfce
          - xorg
          - xrdp
          - xorgxrdp
          - beef-xss
          - firefox-esr
          - curl
          - git
          - vim
          - net-tools
        
        write_files:
          - path: /home/student/.xsession
            content: |
              #!/bin/sh
              exec startxfce4
            owner: student:student
            permissions: '0755'
          
          - path: /home/student/Desktop/BeeF-Instruksjoner.txt
            content: |
              NTNU Datasikkerhet Lab - BeeF Framework
              ==========================================
              
              PÅLOGGING:
              Brukernavn: student
              Passord:    Kali2025
              
              START BeeF:
              sudo beef-xss
              
              BeeF WEB UI:
              http://127.0.0.1:3000/ui/panel
              Login: beef / beef
              
              HOOK URL:
              http://[KALI-IP]:3000/hook.js
              
              DEMO SERVER:
              python3 -m http.server 8080
              
              VIKTIG: Kun for undervisning!
            owner: student:student
            permissions: '0644'
        
        runcmd:
          - systemctl enable xrdp
          - systemctl start xrdp
          - mkdir -p /home/student/Desktop
          - chown -R student:student /home/student
          - touch /home/student/.hushlogin
          - touch /var/lib/cloud/instance/locale-check.skip
          - DEBIAN_FRONTEND=noninteractive apt-get install -y locales-all
        
        power_state:
          mode: reboot
          message: Reboot after setup
          timeout: 30
          condition: True

  kali_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      security_groups: 
        - { get_resource: kali_security_group }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  kali_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: ntnu-internal
      port_id: { get_resource: kali_port }

  win11:
    type: OS::Nova::Server
    properties:
      name: win11-target
      image: 'Windows 11 24H2 Enterprise [Evaluation]'
      flavor: gx3.2c8r
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: win11_port }

  win11_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net }
      security_groups: 
        - { get_resource: kali_security_group }
      fixed_ips:
        - subnet_id: { get_resource: private_subnet }

  win11_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: ntnu-internal
      port_id: { get_resource: win11_port }

outputs:
  connection_info:
    description: Tilkoblingsinformasjon
    value:
      str_replace:
        template: |
          ==========================================
          NTNU DATASIKKERHET LAB
          ==========================================
          
          KALI LINUX:
          RDP:  $kali_ip:3389
          SSH:  ssh student@$kali_ip
          Web:  http://$kali_ip:3000/ui/panel
          User: student / Kali2025
          BeeF: beef / beef
          
          WINDOWS 11:
          RDP:  $win11_ip:3389
          
          NETTVERK:
          Kali Private:   192.168.111.x
          Win11 Private:  192.168.111.x
          
          ==========================================
        params:
          $kali_ip: { get_attr: [ kali_floating_ip, floating_ip_address ] }
          $win11_ip: { get_attr: [ win11_floating_ip, floating_ip_address ] }
  
  kali_public_ip:
    description: Kali public IP
    value: { get_attr: [ kali_floating_ip, floating_ip_address ] }
  
  win11_public_ip:
    description: Windows 11 public IP
    value: { get_attr: [ win11_floating_ip, floating_ip_address ] }
  
  beef_hook_url:
    description: BeeF Hook URL
    value:
      str_replace:
        template: "http://$ip:3000/hook.js"
        params:
          $ip: { get_attr: [ kali_floating_ip, floating_ip_address ] }